#!/bin/bash

function appgetfile {
    return 1
}

function appgetdir {
    return 1
}

function appchoice {
    return 1
}

if ((MODGUI))
then

    function apperror {
        applogger "[ERROR] ${1}"
        ((MODQUIET)) && ! (($2)) && exit 1
        notify-send --icon="error" "${APP}" "$1"
        !(($2)) && exit 1
    }

    function appnotify {
        applogger "[NOTIFY] ${1}"
        ((MODQUIET)) && return
        notify-send --icon="${APPICON}" "${APP}" "$1"
    }

    function appgetfile {
        ((MODQUIET)) && return
        title="${APP}"
        [ ! -z "$1" ] && title="${title}: $1"
        argdir=
        [ "$2" == "dir" ] && argdir="--directory"
        zenity --window-icon="${APPICON}" --title="${title}" --file-selection ${argdir} 2>/dev/null
    }

    function appgetdir {
        appgetfile "$1" "dir"
    }

    function appchoice {
        ((MODQUIET)) && return
        text=$1
        shift
        zenity --window-icon="${APPICON}" --title="${APP}" --list --checklist --text="${text}" --column="checkbox" --column="value" --column="label" --print-column=2 --hide-column=2 --hide-header "$@"  2>/dev/null
    }

    PROGRESSBAR=0
    function appprogress {
        ((MODQUIET)) && return
        if ! ((PROGRESSBAR))
        then
            exec 3> >(zenity --progress --window-icon="${APPICON}" --title="${APP}" --percentage=0 --auto-close 2>/dev/null)
            PROGRESSBAR=1
        fi
        while [ $# -ne 0 ]
        do
            text="$1"
            [ ${#text} -ge 40 ] && text="${text:0:17}...${text: -15}"
            echo "$text" >&3
            if [[ "$text" == "100" ]]
            then
                exec 3>&-
                PROGRESSBAR=0
            fi
            shift
        done
    }

fi
