#!/usr/bin/env bash

SCRIPTPATH="${0}"
[ ${SCRIPTPATH} = 'bash' ] || [ ${SCRIPTPATH} = '/bin/bash' ] && SCRIPTPATH="${BASH_SOURCE}"

APPDIR=$(dirname $(readlink -f "${SCRIPTPATH}"))

source ${APPDIR}/lib/libapp

APP="palias"
APPUSAGE="${APPUSAGE} project action"
PROJECTSDIR="/data/"

current_dir=$(pwd)

project=
action=
args=

function appargscustom {
    project="${1}"
    shift
    action="${1}"
    shift
    args="$@"
}

appargs "$@"

[ -z "${project}" ] && return $(apperror "Project name is mandatory" 1)
projectpath="${PROJECTSDIR}${project}/"
[ -d "${projectpath}" ] || return $(apperror "Project '${project}' not exists" 1)
[ -z "${action}" ] && action="dir"

case "${action}" in
    dir)
        cd "${projectpath}"
        return 0
        ;;
    start)
        [ -e "${projectpath}resources/docker/docker-compose.yml" ] || return $(apperror "No configuration into '${projectpath}resources/docker/docker-compose.yml'")
        cd "${projectpath}resources/docker/"
        docker-compose -p "${project}" build
        docker-compose -p "${project}" up
        ;;
    run|cmd|command)
        [ -e "${projectpath}resources/docker/docker-compose.yml" ] || return $(apperror "No configuration into '${projectpath}resources/docker/docker-compose.yml'")
        cd "${projectpath}resources/docker/"
        container_name=$(echo $args | cut -d' ' -f1)
        [ -z "${container_name}" ] && return $(apperror "Container name is mandatory")
        args=$(echo $args | cut -d' ' -f2-)

        appinfo "${container_name}: Execute '${args}'"

        docker-compose -p "${project}" exec "${container_name}" ${args}
        ;;
    *)
        return $(apperror "Invalid action: '${action}'" 1)
        ;;
esac

cd "${current_dir}"
