#!/bin/bash

APP="SLswitch"
APPDIR=$(dirname $(readlink -f "$0"))

user=`who | grep "(:" | head -n1`
username=`echo "${user}" | cut -d' ' -f1`
display=`echo "${user}" | cut -d'(' -f2 | cut -d')' -f1`

export XAUTHORITY=/home/${username}/.Xauthority
export DISPLAY=${display}.0

source ${APPDIR}/lib/libapp
source ${APPDIR}/lib/libgtk

order=" DP-1 DP1 DVI-I-2 DVI-I-1 DVI-I-2-1 DVI-I-1-1 HDMI1 HDMI-1 HDMI2 HDMI-2 eDP1 eDP-1 "
#order=" DVI-I-2-1 DVI-I-1-1 eDP1 DP1 HDMI1 HDMI2 DVI-I-2 DVI-I-1 "
screens_disconnected=`xrandr | grep "disconnected" | cut -d' ' -f1`
for screen in ${screens_disconnected}
do
    order=${order/ $screen / }
done

screens_connected=`xrandr | grep " connected" | cut -d' ' -f1`
screens_connected=" ${screens_connected} "
screens_connected_order=
for screen in ${order}
do
    [[ ${screens_connected} =~ .*[[:space:]]${screen}[[:space:]].* ]] && screens_connected_order="${screens_connected_order} ${screen}"
done
for screen in ${screens_connected}
do
    [[ ! ${screens_connected_order} =~ .*${screen}.* ]] && screens_connected_order="${screens_connected_order} ${screen}"
done

args=
for screen in ${screens_disconnected}
do
    args="${args} --output ${screen} --off"
done

screens_connected_num=0
rightof=
for screen in ${screens_connected_order}
do
    screens_connected_num=$((${screens_connected_num}+1))
    args="${args} --output ${screen} --auto --rotate normal"
    if [ ${rightof} ]
    then
        args="${args} --right-of ${rightof}"
    else
        args="${args} --primary"
    fi
    rightof=${screen}
done

appinfo "Init screen(s) to order${screens_connected_order}"
xrandr $args

# Set lxpanel monitor
monitor=0
[[ ${screens_connected_num} -gt 2 ]] && monitor=1
appinfo "lxpanel to monitor ${monitor}"
sed -i -e "s/  monitor=.*/  monitor=${monitor}/g" ~/.config/lxpanel/Lubuntu/panels/panel

appinfo "Restart lxpanel"
lxpanelctl restart

appnotify "${screens_connected_order} / ${monitor}"
